AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create Public and Private EC2'

Parameters:
  Environment:
    Type: String
    Description: Environment name
  PublicSubnet1Id:
    Type: String
    Description: Public Subnet 1 ID
  PrivateSubnet1Id:
    Type: String
    Description: Private Subnet 1 ID
  PublicEC2SGId:
    Type: String
    Description: Security Group ID for Public EC2
  PrivateEC2SGId:
    Type: String
    Description: Security Group ID for Private EC2
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of EC2 KeyPair to SSH into instance
  InstanceType:
    Type: String
    Description: EC2 instance type
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t3.micro
      - t3.small
      - t3.medium
  AMI:
    Type: AWS::EC2::Image::Id
    Description: Lastest Amazon Linux 2 AMI ID


Resources:
  PublicEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AMI
      SubnetId: !Ref PublicSubnet1Id
      SecurityGroupIds:
        - !Ref PublicEC2SGId
      KeyName: !Ref KeyName
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-public-ec2

  PrivateEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AMI
      SubnetId: !Ref PrivateSubnet1Id
      SecurityGroupIds:
        - !Ref PrivateEC2SGId
      KeyName: !Ref KeyName
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-private-ec2

Outputs:
  PublicEC2InstanceId:
    Description: Instance ID of Public EC2
    Value: !Ref PublicEC2Instance
  PrivateEC2InstanceId:
    Description: Instance ID of Private EC2
    Value: !Ref PrivateEC2Instance
  PublicEC2IP:
    Description: Public IP of Public EC2
    Value: !GetAtt PublicEC2Instance.PublicIp
  PrivateEC2IP:
    Description: Private IP of Private EC2
    Value: !GetAtt PrivateEC2Instance.PrivateIp
