project:
  name: taskcat
  regions:
    - ${REGION}
  s3_bucket: ${S3_BUCKET}

tests:
  test-lab2:
    template: main.yaml
    parameters:
      Environment: ${ENVIRONMENT}
      AllowedSSHIp: ${ALLOWED_SSH_IP}
      KeyName: ${KEY_NAME}
      AMI: ${AMI_ID}
      BucketName: ${S3_BUCKET}
      Region: ${REGION}
    regions:
      - ${REGION}
