project:
  name: taskcat
  s3_bucket: nt548-lab2-361
  regions:
    - ap-southeast-1
  package_lambda: false

tests:
  test-lab2:
    template: main.yaml
    parameters:
      Environment: dev
      AllowedSSHIp: 104.28.205.71/32
      KeyName: nt548-lab2
      AMI: ami-002fa10fbb7594252
      BucketName: nt548-lab2-361
    regions:
      - ap-southeast-1
