project:
  name: taskcat
  regions:
    - ap-southeast-1
  s3_bucket: nt548-lab2-361

tests:
  test-lab2:
    template: main.yaml
    parameters:
      Environment: dev
      AllowedSSHIp: 104.28.205.71/32
      KeyName: nt548-lab2
      AMI: ami-0004e1ae92a8fdaed
      BucketName: nt548-lab2-361
      Region: ap-southeast-1
    regions:
      - ap-southeast-1
