# This file is used to define the build process for the project.
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12.3
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install cfn-lint taskcat awscli

  pre_build:
    commands:
      - echo "Validating templates with cfn-lint..."
      - cfn-lint main.template.yaml modules/*.yaml *.yaml *.yml

  build:
    commands:
      - echo "Run test with taskcat..."
      - taskcat test run -d
