# This file is used to define the build process for the project.
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install cfn-lint taskcat

  pre_build:
    commands:
      - echo "Linting main.yaml..."
      - if [ -f main.yaml ]; then cfn-lint main.yaml; fi
      - echo "Linting modules/*.yaml..."
      - for file in modules/*.yaml; do [ -f "$file" ] && cfn-lint "$file"; done

  build:
    commands:
      - echo "Run test with taskcat..."
      - taskcat test run -d
