AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create VPC, Subnet, IGW, NAT, Security Groups, EC2'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name
  AllowedSSHIp:
    Type: String
    Description: Your IP address to SSH into Public EC2 (e.g., 1.2.3.4/32)
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 KeyPair name for SSH access
  AMI:
    Type: AWS::EC2::Image::Id
    Description: Lastest Amazon Linux 2 AMI ID
  BucketName:
    Type: String
    Description: S3 bucket name where the module templates are stored

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://nt548-lab2-361.s3.ap-southeast-1.amazonaws.com/modules/1-vpc-subnet.yaml"
      Parameters:
        Environment: !Ref Environment

  IGWPublicRouteStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://nt548-lab2-361.s3.ap-southeast-1.amazonaws.com/modules/2-igw-public-route.yaml"
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnet1Id: !GetAtt VPCStack.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt VPCStack.Outputs.PublicSubnet2Id

  NATGWPrivateRouteStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://nt548-lab2-361.s3.ap-southeast-1.amazonaws.com/modules/3-natgw-private-route.yaml"
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnet1Id: !GetAtt VPCStack.Outputs.PublicSubnet1Id
        PrivateSubnet1Id: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt VPCStack.Outputs.PrivateSubnet2Id

  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://nt548-lab2-361.s3.ap-southeast-1.amazonaws.com/modules/4-security-groups.yaml"
      Parameters:
        Environment: !Ref Environment
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        AllowedSSHIp: !Ref AllowedSSHIp

  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://nt548-lab2-361.s3.ap-southeast-1.amazonaws.com/modules/5-ec2.yaml"
      Parameters:
        Environment: !Ref Environment
        PublicSubnet1Id: !GetAtt VPCStack.Outputs.PublicSubnet1Id
        PrivateSubnet1Id: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        PublicEC2SGId: !GetAtt SecurityGroupsStack.Outputs.PublicEC2SGId
        PrivateEC2SGId: !GetAtt SecurityGroupsStack.Outputs.PrivateEC2SGId
        KeyName: !Ref KeyName
        AMI: !Ref AMI

Outputs:
  VPCId:
    Description: VPC ID
    Value: !GetAtt VPCStack.Outputs.VpcId
  PublicSubnet1Id:
    Description: Public Subnet 1 ID
    Value: !GetAtt VPCStack.Outputs.PublicSubnet1Id
  PublicSubnet2Id:
    Description: Public Subnet 2 ID
    Value: !GetAtt VPCStack.Outputs.PublicSubnet2Id
  PrivateSubnet1Id:
    Description: Private Subnet 1 ID
    Value: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
  PrivateSubnet2Id:
    Description: Private Subnet 2 ID
    Value: !GetAtt VPCStack.Outputs.PrivateSubnet2Id
  PublicEC2SGId:
    Description: Public EC2 Security Group ID
    Value: !GetAtt SecurityGroupsStack.Outputs.PublicEC2SGId
  PrivateEC2SGId:
    Description: Private EC2 Security Group ID
    Value: !GetAtt SecurityGroupsStack.Outputs.PrivateEC2SGId
  PublicRouteTableId:
    Description: Public Route Table ID
    Value: !GetAtt IGWPublicRouteStack.Outputs.PublicRouteTableId
  PrivateRouteTableId:
    Description: Private Route Table ID
    Value: !GetAtt NATGWPrivateRouteStack.Outputs.PrivateRouteTableId
  PublicEC2InstanceId:
    Description: Instance ID of Public EC2
    Value: !GetAtt EC2Stack.Outputs.PublicEC2InstanceId
  PrivateEC2InstanceId:
    Description: Instance ID of Private EC2
    Value: !GetAtt EC2Stack.Outputs.PrivateEC2InstanceId
  PublicEC2IP:
    Description: Public IP of Public EC2
    Value: !GetAtt EC2Stack.Outputs.PublicEC2IP
  PrivateEC2IP:
    Description: Private IP of Private EC2
    Value: !GetAtt EC2Stack.Outputs.PrivateEC2IP
